[package]
name = "marching-cubes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
nalgebra = "0.31.1"
ndarray = "0.13.0"
csv = "1.1"
noise = "0.8.2"
rayon="1.8.1"
evalexpr = "11.3.0"
clap = { version="4.5.1", features = [ "derive" ]}
fidget = "0.3.4"